exclude: ^docs/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/flakeheaven/flakeheaven
  rev: 3.0.0
  hooks:
    - id: flakeheaven
      types: [ python ]
      # Curated list: https://github.com/DmytroLitvinov/awesome-flake8-extensions
      additional_dependencies:
        - bandit
        - flake8-comprehensions
        - flake8-bugbear
        - flake8-use-fstring
        - flake8-pytest
        - flake8-pytest-style
        - flake8-variables-names
        - flake8-cognitive-complexity

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      exclude: ^tests
      additional_dependencies:
        # pydantic classes are used as base classes, so they must be importable by mypy
        - "pydantic"
        - "pytest"
        - "types-PyYAML"
        - "types-freezegun"
        - "types-cryptography"
        - "types-filelock"
        - "types-pytz"
