version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  movie_manager:
    build: ./src/movie_manager
    restart: always
    volumes:
      - ./src/movie_manager/:/movie_manager/
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
      RESET_DB: ${RESET_DB}
      REMOTE_API_URL: ${REMOTE_API_URL}
      REMOTE_API_POLL_INTERVAL: ${REMOTE_API_POLL_INTERVAL}
