version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: --quiet

  movie_manager:
    build: ./src/movie_manager
    restart: always
    volumes:
      - ./src/movie_manager/app:/app
    ports:
      - "8080:80"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/movie_database"
